openapi: 3.1.1
info:
  title: American Football Statistics API
  version: "1.0"

paths:
  /weekly_totals:
    get:
      description: Get weekly player totals for American football
      parameters:
        - name: Year
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/Year"
        - name: Week
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/Week"
        - name: Position
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/Position"
        - name: League
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/PlayerIdentifier"
        - name: PlayerName
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/PlayerName"
      responses:
        "200":
          description: List of weekly player totals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WeeklyTotal"
                title: Response GET weekly_totals
        "422":
          $ref: "#/components/responses/ProblemDetails"
        "500":
          $ref: "#/components/responses/ProblemDetails"

components:
  schemas:
    Year:
      type: string
      title: Year
      description: Season year in YYYY format.
    Week:
      type: integer
      title: Week
    Position:
      type: string
      title: Position
      description: Player position.
    PlayerIdentifier:
      type: string
      title: League
      description: Official player identifier from their league.
    PlayerName:
      type: string
      title: Player Name
      description: Full name of the player.
      maxLength: 120

    WeeklyTotal:
      type: object
      title: WeeklyTotal
      description: Player weekly statistical totals.
      properties:
        Year:
          $ref: "#/components/schemas/Year"
        Week:
          $ref: "#/components/schemas/Week"
        Position:
          $ref: "#/components/schemas/Position"
        PlayerIdentifier:
          $ref: "#/components/schemas/PlayerIdentifier"
        PlayerName:
          $ref: "#/components/schemas/PlayerName"
        PassingTouchdowns:
          type: integer
          description: Number of passing touchdowns.
        PassingYards:
          type: integer
          description: Total passing yards.
        Receptions:
          type: integer
          description: Total receptions.
        ReceivingTouchdowns:
          type: integer
          description: Number of receiving touchdowns.
        ReceivingYards:
          type: integer
          description: Total receiving yards.
        RushingTouchdowns:
          type: integer
          description: Number of rushing touchdowns.
        RushingYards:
          type: integer
          description: Total rushing yards.
      required:
        - Year
        - Week
        - Position
        - League
        - PlayerName
      additionalProperties: false

    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: URI reference identifying the problem type.
        title:
          type: string
          description: A short, human-readable summary of the problem type.
        status:
          type: integer
          description: HTTP status code for this error occurrence.
        detail:
          type: string
          description: Explanation specific to this occurrence of the problem.
        instance:
          type: string
          format: uri-reference
          description: URI reference identifying the specific occurrence of the problem.
      required:
        - title
        - status

  responses:
    ProblemDetails:
      description: Problem Details using RFC 9457
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
